apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: laravel
        - name: MYSQL_DATABASE
          value: laravel
        - name: MYSQL_USER
          value: laravel
        - name: MYSQL_PASSWORD
          value: laravel
        ports:
        - containerPort: 3306
          name: mysql

