apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: migrations
        image: laravel-app-php
        imagePullPolicy: IfNotPresent
        command: ["php",  "artisan", "migrate", "--force"]
        envFrom:
        - secretRef:
            name: laravelapp-secret
      containers:
      - image: laravel-app-nginx
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
      - image: laravel-app-php
        name: php
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: laravelapp-secret
