apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: laravel-app-php
        name: php
        imagePullPolicy: IfNotPresent
        command: ["php", "artisan", "horizon"]
        envFrom:
          - secretRef:
              name: laravelapp-secret
